### ISSUE TITLE
squeaking sound

### ISSUE THREAD

**Issue by lutzbickhardt** [nthx/odroid-xu3-fan-control#2]
Hi!

tried your script on the new XU-4 which is said to be XU-3 compatible. Use it on Ubuntu 15.04.
$uname -a ->
Linux odroid 3.10.82-39 #1 SMP PREEMPT Fri Jul 10 17:47:37 BRT 2015 armv7l armv7l armv7l GNU/Linux

Instead of the fan noise I know get a high frequency squeak (but no fan noise as it stops turning)

**Comment by nthx** [comment]
It might be the file for controlling fan speed has different meaning on XU-4.
I do not posses XU-4. I suggest you do not use this script or adapt it to your needs.

I'm sorry the problem still persists on XU-4 :-(

**Comment by Strit** [comment]
I also tried it on XU4 with Arch Linux ARM, had the same squeking sound. Kill the script, but it didn't return to fan_mode auto. Had to manually do 
sudo echo 1 > /sys/devices/odroid_fan.13/fan_mode
to get it back to automatic.

**Comment by nthx** [comment]
Can you provide me output of these on XU4?

ls -lR /sys/devices/odroid_fan.13/
ls -lR /sys/devices/odroid_fan.14

**Comment by Strit** [comment]
[strit@alarm ~]$ ls -lR /sys/devices/odroid_fan.13/
/sys/devices/odroid_fan.13/:
total 0
lrwxrwxrwx 1 root root    0 Aug  4 12:16 driver -> ../../bus/platform/drivers/odroid-fan
-rwxrwxrwx 1 root root 4096 Aug  4 12:16 fan_mode
-rwxrwxrwx 1 root root 4096 Aug  4 12:16 fan_speeds
-r--r--r-- 1 root root 4096 Aug  4 12:16 modalias
drwxr-xr-x 2 root root    0 Aug  4 12:16 power
-rwxrwxrwx 1 root root 4096 Aug  4 12:16 pwm_duty
-rwxrwxrwx 1 root root 4096 Aug  4 12:16 pwm_enable
lrwxrwxrwx 1 root root    0 Aug  4 10:49 subsystem -> ../../bus/platform
-rwxrwxrwx 1 root root 4096 Aug  4 12:16 temp_levels
-rw-r--r-- 1 root root 4096 Aug  4 10:49 uevent

/sys/devices/odroid_fan.13/power:
total 0
-rw-r--r-- 1 root root 4096 Aug  4 12:16 async
-rw-r--r-- 1 root root 4096 Aug  4 12:16 autosuspend_delay_ms
-rw-r--r-- 1 root root 4096 Aug  4 12:16 control
-r--r--r-- 1 root root 4096 Aug  4 12:16 runtime_active_kids
-r--r--r-- 1 root root 4096 Aug  4 12:16 runtime_active_time
-r--r--r-- 1 root root 4096 Aug  4 12:16 runtime_enabled
-r--r--r-- 1 root root 4096 Aug  4 12:16 runtime_status
-r--r--r-- 1 root root 4096 Aug  4 12:16 runtime_suspended_time
-r--r--r-- 1 root root 4096 Aug  4 12:16 runtime_usage

[strit@alarm ~]$ ls -lR /sys/devices/odroid_fan.14 
ls: cannot access /sys/devices/odroid_fan.14: No such file or directory

**Comment by nthx** [comment]
OK. Thanks. So there is difference between XU3 here.
Can you provide these too please?

ls -l /sys/devices/ | grep tmu
ls -l /sys/devices/_tmu
cat /sys/devices/_tmu/

Last one as root, or via sudo...:
sudo cat /sys/devices/*tmu/

**Comment by Strit** [comment]
Here you go
[strit@alarm ~]$ ls -l /sys/devices/ | grep tmu
drwxr-xr-x  3 root root 0 Aug  4 10:49 10060000.tmu

[strit@alarm ~]$ ls -l /sys/devices/*tmu
total 0
lrwxrwxrwx 1 root root    0 Aug  4 12:38 driver -> ../../bus/platform/drivers/exynos-tmu
-r--r--r-- 1 root root 4096 Aug  4 12:38 modalias
drwxr-xr-x 2 root root    0 Aug  4 12:38 power
lrwxrwxrwx 1 root root    0 Aug  4 10:49 subsystem -> ../../bus/platform
-r--r----- 1 root root 4096 Aug  4 12:38 temp
-rw-r--r-- 1 root root 4096 Aug  4 10:49 uevent

[strit@alarm ~]$ sudo cat /sys/devices/*tmu/
[sudo] password for strit: 
cat: /sys/devices/10060000.tmu/: Is a directory

**Comment by nthx** [comment]
Thanks for reply.
I do not have XU4. I could risk damaging users devices if I would make any support for it "blindly".

I suggest you try yourself to find proper control files for temperature and fan control. It should be straightforward.

If you find and confirm that it works on your XU4 please do a pull request, or provide me the changes you did to the script. I will merge.

I can't do much besides that without risking damaging hardware. Take care

**Comment by Strit** [comment]
Np, I won't really have time to do much about this myself. So far, I just put it on the attic. That way we can't hear it. :)
