### ISSUE TITLE
Works on XU4

### ISSUE THREAD

**Issue by icebob** [nthx/odroid-xu3-fan-control#3]
If I changed `odroid_fan.14` to `odroid_fan.13` it works on Odroid XU4 too.

```
FAN_MODE_FILE="/sys/devices/odroid_fan.13/fan_mode"
FAN_SPEED_FILE="/sys/devices/odroid_fan.13/pwm_duty"
```

**Comment by nthx** [comment]
Are you able to provide a pull request?

A change in the script that tries to test if *fan.13 or *fan.14 exist.
Based on that it uses one or another..

**Comment by icebob** [comment]
PR https://github.com/nthx/odroid-xu3-fan-control/pull/4
